[tool.poetry]
name = "photosynthesisai"
version = "0.1.0"
description = ""
authors = ["Scott <scott.vinay.93@gmail.com>"]
readme = "README.md"

packages = [
  { include = "psai", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.11"
numpy = "<2"
pandas = ">=2.3.0,<3.0.0"
gymnasium = "1.0.0"
pytest = "^8.4.1"
setuptools = "^80.9.0"
matplotlib = "^3.10.3"
torch = "2.2.2"
stable-baselines3 = "2.4.1"
sb3-contrib = "==2.4.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
